//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasaAPOD.NasaAPODService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NasaAPODService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPOD", ReplyAction="http://tempuri.org/IService1/getAPODResponse")]
        string getAPOD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPOD", ReplyAction="http://tempuri.org/IService1/getAPODResponse")]
        System.Threading.Tasks.Task<string> getAPODAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODTitle", ReplyAction="http://tempuri.org/IService1/getAPODTitleResponse")]
        string getAPODTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODTitle", ReplyAction="http://tempuri.org/IService1/getAPODTitleResponse")]
        System.Threading.Tasks.Task<string> getAPODTitleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODExp", ReplyAction="http://tempuri.org/IService1/getAPODExpResponse")]
        string getAPODExp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODExp", ReplyAction="http://tempuri.org/IService1/getAPODExpResponse")]
        System.Threading.Tasks.Task<string> getAPODExpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODDate", ReplyAction="http://tempuri.org/IService1/getAPODDateResponse")]
        string getAPODDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAPODDate", ReplyAction="http://tempuri.org/IService1/getAPODDateResponse")]
        System.Threading.Tasks.Task<string> getAPODDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldImage", ReplyAction="http://tempuri.org/IService1/getOldImageResponse")]
        string getOldImage(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldImage", ReplyAction="http://tempuri.org/IService1/getOldImageResponse")]
        System.Threading.Tasks.Task<string> getOldImageAsync(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldTitle", ReplyAction="http://tempuri.org/IService1/getOldTitleResponse")]
        string getOldTitle(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldTitle", ReplyAction="http://tempuri.org/IService1/getOldTitleResponse")]
        System.Threading.Tasks.Task<string> getOldTitleAsync(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldExp", ReplyAction="http://tempuri.org/IService1/getOldExpResponse")]
        string getOldExp(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldExp", ReplyAction="http://tempuri.org/IService1/getOldExpResponse")]
        System.Threading.Tasks.Task<string> getOldExpAsync(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldDate", ReplyAction="http://tempuri.org/IService1/getOldDateResponse")]
        string getOldDate(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOldDate", ReplyAction="http://tempuri.org/IService1/getOldDateResponse")]
        System.Threading.Tasks.Task<string> getOldDateAsync(string year, string month, string day);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NasaAPOD.NasaAPODService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NasaAPOD.NasaAPODService.IService1>, NasaAPOD.NasaAPODService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAPOD() {
            return base.Channel.getAPOD();
        }
        
        public System.Threading.Tasks.Task<string> getAPODAsync() {
            return base.Channel.getAPODAsync();
        }
        
        public string getAPODTitle() {
            return base.Channel.getAPODTitle();
        }
        
        public System.Threading.Tasks.Task<string> getAPODTitleAsync() {
            return base.Channel.getAPODTitleAsync();
        }
        
        public string getAPODExp() {
            return base.Channel.getAPODExp();
        }
        
        public System.Threading.Tasks.Task<string> getAPODExpAsync() {
            return base.Channel.getAPODExpAsync();
        }
        
        public string getAPODDate() {
            return base.Channel.getAPODDate();
        }
        
        public System.Threading.Tasks.Task<string> getAPODDateAsync() {
            return base.Channel.getAPODDateAsync();
        }
        
        public string getOldImage(string year, string month, string day) {
            return base.Channel.getOldImage(year, month, day);
        }
        
        public System.Threading.Tasks.Task<string> getOldImageAsync(string year, string month, string day) {
            return base.Channel.getOldImageAsync(year, month, day);
        }
        
        public string getOldTitle(string year, string month, string day) {
            return base.Channel.getOldTitle(year, month, day);
        }
        
        public System.Threading.Tasks.Task<string> getOldTitleAsync(string year, string month, string day) {
            return base.Channel.getOldTitleAsync(year, month, day);
        }
        
        public string getOldExp(string year, string month, string day) {
            return base.Channel.getOldExp(year, month, day);
        }
        
        public System.Threading.Tasks.Task<string> getOldExpAsync(string year, string month, string day) {
            return base.Channel.getOldExpAsync(year, month, day);
        }
        
        public string getOldDate(string year, string month, string day) {
            return base.Channel.getOldDate(year, month, day);
        }
        
        public System.Threading.Tasks.Task<string> getOldDateAsync(string year, string month, string day) {
            return base.Channel.getOldDateAsync(year, month, day);
        }
    }
}
